version: '3.8'
services:
#  mongodb:
#    image: mongo
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#     image: mongo-express
#     ports:
#       - "8081:8081"
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_SERVER: mongodb
#       ME_CONFIG_BASICAUTH_USERNAME: admin
#       ME_CONFIG_BASICAUTH_PASSWORD: pass
#     depends_on:
#       - mongo
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker-db
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - database
  oracle:
    container_name: oracle
    image: oracle/database:21.3.0-xe
    restart: always
    environment:
      ORACLE_PWD: welcome123
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - '1521:1521'
    depends_on:
      - postgres
    networks:
      - database
#  mysql:
#    container_name: mysql
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: db
#      MYSQL_USER: coti
#      MYSQL_PASSWORD: coti
#      MYSQL_ROOT_PASSWORD: coti
#    ports:
#      - '3307:3307'
#    depends_on:
#      - oracle
#    networks:
#      - database
networks:
  database:
    driver: bridge
volumes:
  pg-data:
