server:
  port: 1234

spring:
  application:
    name: multi-database
  datasource:
    oracle:
      jdbcUrl: jdbc:oracle:thin:@localhost:1521/xe?serverTimezone=UTC&useSSL=false
      username: SYS AS SYSDBA
      password: welcome123
      driver-class-name: oracle.jdbc.OracleDriver
    postgres:
      jdbcUrl: jdbc:postgresql://localhost:5432/multidb
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: multidb
      username: root
      password: example
      uri: mongodb://root:example@localhost:27017
  output:
    ansi:
      enabled: Always